#spring:
#  profiles: dev

mq:
  env: dev
  env.diat: b2c    
  config:
    exchange: log.direct
    queue:
      error: log.error
      error.routing: log.error.routing
      error.routing.key: log.error.routing.key
      info: log.info
      info.routing: log.info.routing
      info.routing.key: log.info.routing.key

user: 
  id: 100
  username: aa
  password: 123456
  birthday: 2001/12/1
  sex: true
  list: [A,B,C]
  map: {name: sam, age: 18}
  address: 
    id: 100
    detail: asdf