server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: false
      hibernate:
        ddl-auto: update
        

