server:
  port: 8088
  servlet:
    context-path: /aaa

user: 
  id: 100
  username: aa
  password: 123456
  birthday: 2001/12/1
  sex: true
  list: [A,B,C]
  map: {name: sam, age: 18}
  address: 
    id: 100
    detail: asdf
debug: true

  
    
    