spring: 
  application: 
    name: springboot-rabbitmq
  rabbitmq: 
    host: 192.168.78.150
    port: 5672
    username: zhouhy
    password: zhouhy
mq:
  config:
    exchange: log.fanout
    queue:
      sms: log.error      
      push: log.info      
      


